### ISSUE TITLE
Simultaneously record video and process frames

### ISSUE THREAD

**Issue by fabiomaia** [tanersener/flutter-ffmpeg#121]
I would like to

- capture camera input on Android and iOS
- simultaneously record video and arbitrarily process captured frames

This is not possible with the MediaRecorder API in Android. But if this use case is possible with ffmpeg I will dive deep into this package and my company would be interested in backing you to continue developing and supporting this package.

What parts of ffmpeg do I need to become familiar with to develop this?

**Comment by tanersener** [comment]
Can you give some more details about processing you're planning to do?

This library can be used in two different ways:

1. The first way is to define an `ffmpeg` command and run it. This command can include recording/processing and other stuff. This is how most of the users are using this library. It is easier compared to 2.

2. The second way is to develop a native (C/C++) application or plugin, by accessing `ffmpeg` headers & libraries directly and run that application. This application will achieve the same functionality, but instead of using a command it will make `ffmpeg` API calls.

Other than that, some users complain about two things about using this library. I'm not sure whether they important for you or not.

1- The first difficulty is `Android` camera support. Unfortunately, not all `Android` cameras are supported by the library. This limitation is not coming from the library itself. It is from `Android NDK's Native API`. As explained in the [Android NDK Native API](https://developer.android.com/ndk/guides/stable_apis#camera) documentation, `devices with deprecated camera HAL 1.0 implementations (camera devices that have the LEGACY hardware level) are not supported`.

2- The second difficulty for users that want to record videos is it is not possible to display/play the video that is being recorded at that moment.

**Comment by fabiomaia** [comment]
Essentially, I want to do real-time object detection (i.e., take the camera frames and run them through a neural network to get bounding boxes which I would then draw on the screen for the user on top of the video) and simultaneously later save the video of what was recorded.

Saving the video does not necessarily have to be immediate, it doesn't have to be available to the user immediately after stopping recording. It's okay if the video is somehow only saved afterwards in the background (maybe by accumulating the video frames and reconstructing the video in the background or something like that).

**Comment by tanersener** [comment]
You need to call `ffmpeg` API to get the frames. It is not an easy development. Have you considered using another library, `opencv` for example can be used to both get the camera frames and detect the objects?

**Comment by fabiomaia** [comment]
OpenCV is not an option as we need our own custom object detection.

But something like this should be quite feasible with this plugin, no? I can show the video preview and overlay the object detection with another library, while also getting the frames to feed into ffmpeg like this https://stackoverflow.com/questions/15280722/android-camera-capture-using-ffmpeg

**Comment by tanersener** [comment]
Solution used in that `stackoverflow` thread, uses Android's `Camera` API to get the frame from the camera. Then sends `byte[]` data to `ffmpeg` using a `pipe`.

You can try using the same approach if it works for you.
