### ISSUE TITLE
Flutter-ffmpeg with FijkPlayer

### ISSUE THREAD

**Issue by aytunch** [tanersener/flutter-ffmpeg#219]
Hi Taner:)

I have read the article you shared: [Using Multiple FFmpeg Implementations In The Same iOS Application](https://github.com/tanersener/mobile-ffmpeg/wiki/Using-Multiple-FFmpeg-Implementations-In-The-Same-iOS-Application) however I am still struggling. Seems like my situation falls into the 2nd category. I have created and shared a repo down below with minimal code(only main.dart) for everyone to experience the issue. If you would like me to post the logs and flutter doctor outputs, I gladly can.

I want to compress, downsize and extract the first frame of a video using ffmpeg. Actually I can successfully do 
these with the help of your package. The problem arises when I add FijkPlayer(or any other video players that 
depend on ffmpeg) to the project. Especially on iOS, the project crashes the moment we make a method call from flutter code. I know you are aware of this problem and I saw you saying that it would take a lot of effort to support 2 different ffmpeg frameworks many times while browsing the issues. 

I would like to know what the main cause of this error is. Is it because of FijkPlayer depending on ffmpeg3.x and flutter_ffmpeg depending on version 4.x? If that is the case, is there a simple solution as to upgrade/downgrade FijkPlayer's or flutter_ffmpeg's the base ffmpeg version? If compiled with the same version, would we be able to
use both flutter_ffmpeg and fijkplayer in the same project? I saw this section in the readme of IjkPlayer which is the native parent of FijkPlayer [which shows how to compile ijkplayer with different ffmpeg versions](https://github.com/befovy/ijkplayer#build-android). Do you think this is useful for our case?

Hoping that the above method solves our problems, how hard do you think changing the versions and compiling will be? Is it a straightforward process. Since I am not too familiar with this process, I want to know before getting in any deeper. For instance what makes VLCPlayer work with flutter_ffmpeg and not other video player libraries that depend on ffmpeg? I would be really grateful if you could enlighten us about this issue. I am pretty sure that a lot of people who use a video player in their app also need to use an encoding solution and vice-versa. And a lot of people can benefit from a possible solution.

They say one repo is worth a thousand words:) [FFmpeg with FijkPlayer Repo](https://github.com/ikartech/ffmpeg-fijk) So we made a very simple project which records a video using the camera plugin, then encodes this video using flutter_ffmpeg and lastly, displays this encoded video using FijkPlayer package. When you compile this simple project on iOS you will see the error. Please let me know if you need more info on the error and want me to try and test different things.

Lastly, I would like to add a very similar issue opened in FijkPlayer's repo. The author @befovy also [stated that this is a hard task in this issue](https://translate.googleusercontent.com/translate_c?depth=1&pto=aue&rurl=translate.google.com&sl=zh-CN&sp=nmt4&tl=en&u=https://github.com/befovy/fijkplayer/issues/246&usg=ALkJrhhLSv3eYReDAsbCQA5y8ww8II71Qg#issuecomment-636426230). While this makes me kind of sad, still it shows that there is still hope:) 

Thanks.

**Comment by tanersener** [comment]
I don't have a definite answer for you. Because the situation with `FijkPlayer` is a little different. It is a special version of case number 1 in my wiki. 

When I try to run your test application I see the following error. Which is about SDL. SDL is not included in `flutter-ffmpeg` or `mobile-ffmpeg`, but `FijkPlayer` has it. And what makes SDL special is the way it runs inside `ffmpeg`. It changes the entry point of the applications. In order to do that specific threads are created when the libraries are loaded. Those threads call the `ffmpeg` functions like callbacks. I suspect this is the main reason why these two libraries don't work together. The author of `FijkPlayer` may have a better idea about what is exactly wrong there. Because there is a complex method chain used for initialisation in `BIJKPlayer`. It is hard to understand it on my side.

You may try building `BIJKPlayer` with the same ffmpeg version that `mobile-ffmpeg` uses and it may improve the situation but I'm not 100 % sure. Because of that SDL issue.

<img width="275" alt="Screenshot 2020-10-26 at 21 41 46" src="https://user-images.githubusercontent.com/10158439/97235684-4eaa6a80-17db-11eb-93b5-69f458621ecd.png">

**Comment by aytunch** [comment]
@tanersener thank you very much for this very valuable insight on the subject. While I try to grasp all the points you have mentioned and start searching what the heck a SDL is, I would like to ask Befovy for his opinion on the subject too. @befovy I hope that I am not bothering you mentioning like this on another library. But I know that you had this issue in your radar. So I thought it is best if authors of these two great packages exchange ideas for the sake of their users:)
