### ISSUE TITLE
Difference between execute() and executeAsync() in terms of Isolates and UI Thread

### ISSUE THREAD

**Issue by aytunch** [tanersener/flutter-ffmpeg#224]
Hi Taner,

I want to get rid of the Jank in the UI thread in my iOS app. Right now I am using execute(). I read the documentation and did not find a part talking about threads.

Both execute() and executeAsync() are async functions under the hood. So is the only difference syntactic?

Is there a way to move my encoding to an Isolate, from the UI thread, so that Ui is more smooth? If this is possible, would I still be able to listen the progress of the encoding process?

Extra: Is there a way to allow execution while app is in the background or terminated? Afaik this is OS specific issue and for instance iOS allows only device specific features like location/bluetooth etc for background modes. 

Thanks.

**Comment by tanersener** [comment]
> Both execute() and executeAsync() are async functions under the hood. So is the only difference syntactic?

Yes, they are the same in terms of speed and performance. The only difference is their response. `executeAsync()` returns an `executionId` that you can use to `cancel` that specific execution. 

> Is there a way to move my encoding to an Isolate, from the UI thread, so that Ui is more smooth? If this is possible, would I still be able to listen the progress of the encoding process?

Well, I haven't tried using isolates in my applications. However, if flutter allows you to call a native plugin from isolates then it shouldn't be a problem. The plugin itself uses internal threads to run the executions. I don't think it will have an effect on UI though.

I don't know the answer of your last question. As far as I know, Android allows threads to continue running when application is in the background. But if they consume too much CPU/RAM they can be killed. Because `foreground` applications have the priority in terms of CPU/RAM.

**Comment by aytunch** [comment]
> The plugin itself uses internal threads to run the executions. I don't think it will have an effect on UI though.

So does the `execute()` function work on a thread different from the UI thread in Flutter for both iOS and Android? If that's the case, spawning an isolate and running `execute()` inside of the isolate would not change much in terms of fps.
Do you think it is worth trying to put flutter_ffmpeg execute inside an isolate and see if there is a difference?

**Comment by tanersener** [comment]
Yes, threads from platform specific thread pools run the native `ffmpeg` process and they do the actual work. If you already use isolates somewhere in your app I suggest calling `flutter_ffmpeg` there. If won't be too difficult for you. 

As I've said, I don't expect to see any improvement there. But, maybe calling a plugin with platform specific code from isolates is faster than calling it from UI thread. I don't know that. You can see that by running this test.
