### ISSUE TITLE
[Help] Prevent app to get killed by os !

### ISSUE THREAD

**Issue by shofizone** [tanersener/flutter-ffmpeg#280]
**Description**
I am working on a video compressing app. The problem is the app is get killed when screen is off and also when app is running in background (eg. User is using another app but compression is running).

**Expected behavior**
I want that if app could run in background or  compression could run in background  even after app is closed. But user should have control over it,  like a music player 

I am sorry for creating issue like that, But other developer might face similar problem. So help/discussion is highly appreciated. Thank you !

**Comment by thegrxp** [comment]
This has nothing to do with this library, the problem is that your code is not executed in a service.

Here is an example with Geofencing
https://medium.com/flutter/executing-dart-in-the-background-with-flutter-plugins-and-geofencing-2b3e40a1a124

More about services on Android
https://developer.android.com/guide/components/services#Types-of-services
