### ISSUE TITLE
app crashes on iOS

### ISSUE THREAD

**Issue by romater0** [tanersener/flutter-ffmpeg#293]
**Current behavior**
The app crashes when the following command to crop a video is executed 
_flutterFFmpeg.execute('-i ${widget.picked.path} -ss ${timeBoxControllerStart.text} -t ${durationFormatter(difference)} -c copy $outPath')

**Logs**
https://ghostbin.co/paste/r2wsjha

**Environment**
Flutter doctor output
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (2 available)
    ! Error: iPhone is busy: Copying cache files from device. Xcode will continue when iPhone is finished. (code -10)

• No issues found!

**Other**
code ::: 

 _flutterFFmpeg.execute('-i ${widget.picked.path} -ss ${timeBoxControllerStart.text} -t ${durationFormatter(difference)} -c copy $outPath')

**Comment by tanersener** [comment]
Your application crashes because it includes two `ffmpeg` implementations. One implementation comes from `flutter_ffmpeg` s parent project `mobile-ffmpeg`. The other one comes from `ijkplayer`. 

See [Using Multiple FFmpeg Implementations In The Same iOS Application](https://github.com/tanersener/mobile-ffmpeg/wiki/Using-Multiple-FFmpeg-Implementations-In-The-Same-iOS-Application) wiki page and try to apply solutions given there.

**Comment by romater0** [comment]
Thanks , fixed it
