### ISSUE TITLE
Using ffmpeg for Flutter Desktop

### ISSUE THREAD

**Issue by hariangr** [tanersener/flutter-ffmpeg#70]
Is it possible to use this package to run ffmpeg command on flutter desktop app? Like on Windows MacOs and Linux?

**Comment by tanersener** [comment]
Unfortunately no

**Comment by hariangr** [comment]
hmmm... is it possible to achieve this goal? (Like for example, using dart:ffi) or is it simply not currently possible?

**Comment by tanersener** [comment]
I'm planning to add `Desktop` support when all three platforms (macOS, Windows, Linux) becomes stable. According to [Flutter Desktop shells](https://github.com/flutter/flutter/wiki/Desktop-shells) documentation, only `macOS` platform is mature enough. The other two, `Windows` and `Linux`, are in early stages and expected to radically change over time.

**Comment by SwissCheese5** [comment]
https://medium.com/dartlang/dart2native-a76c815e6baf
I'm not sure if this is relevant at all, but you can now make command line commands with flutter, can this help flutterffmpeg port to all other platforms?

**Comment by tanersener** [comment]
@SwissCheese5 thanks for posting this article. It's an important step in the right direction but this project is using native SDKs to build `ffmpeg` and does not need a tool like `dart2native`. So we won't be able to use it.

**Comment by winwisely99** [comment]
There are quite s few flutter projects supporting web, desktop and mobile.
Here is s good example that's well written.

https://github.com/crazecoder/open_file

Video is not easy compared to file.
But there is s video player that works on Mac and Linux and soon windows. It works on mobile and web now.

https://github.com/cloudwebrtc/flutter-webrtc/tree/master/example

There is a small glfw bug on windows I believe. The fix is upstream in flutter engine but not released yet. Soon I think though

**Comment by Napolitain** [comment]
Hi, any updates on this? Having this to use RTX NVENC would be neat also !

**Comment by DrSensor** [comment]
Is it already implemented?

**Comment by tanersener** [comment]
See #156
