### ISSUE TITLE
Possible to use libx264?

### ISSUE THREAD

**Issue by jgv115** [tanersener/flutter-ffmpeg#9]
Hi there,

In the examples, the 'mpeg4' encoder is always used. However, on the internet most examples have 'libx264' which seems to be the norm. However, when I try to use this I always get "Unknown encoder 'libx264'"

Is this because this encoder is not built into the package? If so, what other encoders can I use.

Thanks!

**Comment by tanersener** [comment]
There are 8 different `flutter-ffmpeg` packages available. `x264` is included in packages with `-gpl` postfix because it is licensed under `GPL`. [Features](https://github.com/tanersener/flutter-ffmpeg#1-features) section in README lists all external libraries enabled in each package. Refer to [Packages](https://github.com/tanersener/flutter-ffmpeg#21-packages) section to see how a`flutter-ffmpeg` package can be installed.

**Comment by jgv115** [comment]
Hi tanersener,

Thank you for this information. I changed the path to `packages/flutter_ffmpeg_https-gpl` and now I can use the libx264 encoder.

Thanks very much for your support of this plugin.
